#!/usr/bin/env bash
#configuring web 01 with custom http response header

#updating packages
sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'

# Creating an index page
sudo echo "Holberton School" | sudo tee /var/www/html/index.html

# Performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\\/github.com\/edith permanent;"
sudo sed -i "s/server_name _; /$new_string/" /etc/nginx/sites-enabled/default

# Creating a custom error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
page="listen 80 default_server;\\n\\terror_page 404 /404.html;\\n\\tlocation = /404.html {\\n\\t\\troot /var/www/html;\\n\\t\\tinternal;\\n\\t}"
sudo sed -i "s|listen 80 default_server;|$page|" /etc/nginx/sites-available/default


# Custom HTTP response header

sudo sed -i "server_name _; /a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
# Test for syntax errors
sudo nginx -t

# Restart nginx
sudo service nginx restart
