#!/usr/bin/env bash
 sudo apt-get update 
sudo apt-get install -y nginx

echo"Holberton school" sudo tee /var/www/html/index.html

string_for_replacement="server_name -;\n\trewrite ^\/\/github.com\/edith permanent;"

sudo sed -i "s/server_name -;$string_for_replacement/" /etc/nginx/sites-enabled/defaulr

sudo service nginx
